name: .NET publish main branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '10-40 2 * * *'
  
jobs:
  build:
    strategy:
        fail-fast: true
        matrix: 
            # os: [main, W10532]
            os: [main, W10532]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4
    - name: Stop tNavigatorComputingNode.exe
      shell: cmd
      continue-on-error: true
      run: taskkill /F /im tNavigatorComputingNode.exe

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: tNavigatorComputingNode
      run: dotnet restore 

    - name: Build
      working-directory: tNavigatorComputingNode
      run: dotnet build --no-restore

    - name: Publish
      working-directory: tNavigatorComputingNode
      run: dotnet publish tNavigatorComputingNode.csproj /p:PublishProfile=FolderProfile.pubxml

    - name: Create task scheduler
      shell: cmd
      working-directory: tNavigatorComputingNode
      continue-on-error: true
      run: schtasks /create /ru hw\kosacheviv /rp kos4v /xml .\tnav_node_oilcase.xml /tn tnav_node_oilcase 

    - name: Copy dir 
      shell: cmd
      working-directory: tNavigatorComputingNode
      run: xcopy /E /I /Y .\out  C:\tNavNodeOilCase

    - name: Start tNavigatorComputingNode.exe
      shell: cmd
      run: schtasks /run /tn tnav_node_oilcase

