name: .NET publish app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Stop tNavigatorComputingNode.exe
      shell: cmd
      continue-on-error: true
      run: taskkill /F /im tNavigatorComputingNode.exe

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c Release -o out
    - name: Copy dir 
      shell: cmd
      run: xcopy /E /I /Y .\tNavigatorComputingNode\out  C:\tNavNode
    - name: Start tNavigatorComputingNode.exe
      shell: cmd
      run: |
        cd C:\tNavNode
        Start /b C:\tNavNode\tNavigatorComputingNode.exe
