name: .NET publish app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Stop tNavigatorComputingNode.exe
    #   run: pwsh -Command Stop-Process -Name "tNavC*"

    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: 8.0.x
    # - name: Restore dependencies
    #   run: dotnet restore
    # - name: Build
    #   run: dotnet build --no-restore
    # - name: Publish
    #   run: dotnet publish -c Release -o out
    - name: Copy dir 
      shell: cmd
      run: xcopy /s /y .\out\*  c:\tNavNode
    # - name: Start tNavigatorComputingNode.exe
    #   run: Start /b C:\tNavNode\tNavigatorComputingNode.exe
